<?php

return [
    'groups' => [
        'company-settings' => [
            'label' => 'Company Settings',
            'description' => 'Core organization identity and contact details.',
            'icon' => 'building-2',
            'color' => 'indigo',
            'fields' => [
                ['key' => 'company.name', 'label' => 'Company Name', 'type' => 'text', 'default' => 'Aashish Pathak'],
                ['key' => 'company.legal_name', 'label' => 'Legal Name', 'type' => 'text'],
                ['key' => 'company.email', 'label' => 'Company Email', 'type' => 'text'],
                ['key' => 'company.phone', 'label' => 'Company Phone', 'type' => 'text'],
                ['key' => 'company.website', 'label' => 'Website', 'type' => 'text'],
                ['key' => 'company.tax_id', 'label' => 'Tax ID / VAT Number', 'type' => 'text'],
                ['key' => 'company.address', 'label' => 'Address', 'type' => 'text', 'input' => 'textarea'],
                ['key' => 'company.timezone', 'label' => 'Timezone', 'type' => 'select', 'options' => ['UTC' => 'UTC', 'Asia/Dhaka' => 'Asia/Dhaka', 'Asia/Kolkata' => 'Asia/Kolkata', 'Europe/London' => 'Europe/London', 'America/New_York' => 'America/New York']],
            ],
        ],

        'financial-settings' => [
            'label' => 'Financial Settings',
            'description' => 'Currency, tax, rounding, and ledger defaults.',
            'icon' => 'dollar-sign',
            'color' => 'emerald',
            'fields' => [
                ['key' => 'financial.base_currency', 'label' => 'Base Currency', 'type' => 'select', 'options' => ['USD' => 'USD', 'EUR' => 'EUR', 'GBP' => 'GBP', 'BDT' => 'BDT', 'INR' => 'INR']],
                ['key' => 'financial.currency_position', 'label' => 'Currency Position', 'type' => 'select', 'options' => ['prefix' => 'Prefix', 'suffix' => 'Suffix']],
                ['key' => 'financial.decimal_places', 'label' => 'Decimal Places', 'type' => 'number'],
                ['key' => 'financial.default_tax_rate', 'label' => 'Default Tax Rate (%)', 'type' => 'number'],
                ['key' => 'financial.rounding_mode', 'label' => 'Rounding Mode', 'type' => 'select', 'options' => ['half_up' => 'Half Up', 'half_down' => 'Half Down', 'bankers' => 'Bankers']],
                ['key' => 'billing.currency', 'label' => 'Billing Currency', 'type' => 'select', 'options' => ['USD' => 'USD', 'EUR' => 'EUR', 'GBP' => 'GBP', 'BDT' => 'BDT', 'INR' => 'INR']],
            ],
        ],

        'email-smtp-settings' => [
            'label' => 'Email & SMTP Settings',
            'description' => 'Mail sender identity and SMTP transport settings.',
            'icon' => 'mail',
            'color' => 'sky',
            'fields' => [
                ['key' => 'email.from_name', 'label' => 'From Name', 'type' => 'text'],
                ['key' => 'email.from_address', 'label' => 'From Address', 'type' => 'text'],
                ['key' => 'smtp.host', 'label' => 'SMTP Host', 'type' => 'text'],
                ['key' => 'smtp.port', 'label' => 'SMTP Port', 'type' => 'number'],
                ['key' => 'smtp.username', 'label' => 'SMTP Username', 'type' => 'text'],
                ['key' => 'smtp.password', 'label' => 'SMTP Password', 'type' => 'text'],
                ['key' => 'smtp.encryption', 'label' => 'SMTP Encryption', 'type' => 'select', 'options' => ['tls' => 'TLS', 'ssl' => 'SSL', 'none' => 'None']],
            ],
        ],

        'notification-settings' => [
            'label' => 'Notification Settings',
            'description' => 'Global notification behavior and channels.',
            'icon' => 'bell',
            'color' => 'amber',
            'fields' => [
                ['key' => 'notification.email_enabled', 'label' => 'Enable Email Notifications', 'type' => 'boolean', 'input' => 'toggle'],
                ['key' => 'notification.sms_enabled', 'label' => 'Enable SMS Notifications', 'type' => 'boolean', 'input' => 'toggle'],
                ['key' => 'notification.push_enabled', 'label' => 'Enable Push Notifications', 'type' => 'boolean', 'input' => 'toggle'],
                ['key' => 'notification.daily_digest_enabled', 'label' => 'Enable Daily Digest', 'type' => 'boolean', 'input' => 'toggle'],
                ['key' => 'notification.daily_digest_time', 'label' => 'Daily Digest Time', 'type' => 'text'],
                ['key' => 'notification.admin_alert_email', 'label' => 'Admin Alert Email', 'type' => 'text'],
            ],
        ],

        'branding-settings' => [
            'label' => 'Branding Settings',
            'description' => 'Brand identity, logos, and visual presentation.',
            'icon' => 'palette',
            'color' => 'rose',
            'fields' => [
                ['key' => 'branding.logo', 'label' => 'Primary Logo', 'type' => 'image'],
                ['key' => 'branding.favicon', 'label' => 'Favicon', 'type' => 'image'],
                ['key' => 'branding.logo_dark', 'label' => 'Dark Mode Logo', 'type' => 'image'],
                ['key' => 'branding.primary_color', 'label' => 'Primary Color', 'type' => 'text', 'input' => 'color', 'default' => '#4f46e5'],
                ['key' => 'branding.secondary_color', 'label' => 'Secondary Color', 'type' => 'text', 'input' => 'color', 'default' => '#0ea5e9'],
                ['key' => 'branding.custom_css', 'label' => 'Custom CSS JSON', 'type' => 'json', 'input' => 'textarea'],
            ],
        ],

        'file-storage-settings' => [
            'label' => 'File Storage Settings',
            'description' => 'Upload handling and storage provider defaults.',
            'icon' => 'database',
            'color' => 'cyan',
            'fields' => [
                ['key' => 'storage.default_disk', 'label' => 'Default Storage Disk', 'type' => 'select', 'options' => ['public' => 'Public', 'local' => 'Local', 's3' => 'S3']],
                ['key' => 'storage.max_upload_mb', 'label' => 'Max Upload Size (MB)', 'type' => 'number'],
                ['key' => 'storage.allowed_file_types', 'label' => 'Allowed File Types (JSON)', 'type' => 'json', 'input' => 'textarea'],
                ['key' => 'storage.private_uploads', 'label' => 'Private Uploads', 'type' => 'boolean', 'input' => 'toggle'],
                ['key' => 'storage.s3_bucket', 'label' => 'S3 Bucket', 'type' => 'text'],
                ['key' => 'storage.s3_region', 'label' => 'S3 Region', 'type' => 'text'],
            ],
        ],

        'app-preferences' => [
            'label' => 'App Preferences',
            'description' => 'Global UX preferences and defaults.',
            'icon' => 'sliders-horizontal',
            'color' => 'slate',
            'fields' => [
                ['key' => 'app.default_language', 'label' => 'Default Language', 'type' => 'select', 'options' => ['en' => 'English', 'bn' => 'Bangla', 'es' => 'Spanish']],
                ['key' => 'app.default_date_format', 'label' => 'Default Date Format', 'type' => 'select', 'options' => ['Y-m-d' => 'YYYY-MM-DD', 'd/m/Y' => 'DD/MM/YYYY', 'm/d/Y' => 'MM/DD/YYYY']],
                ['key' => 'app.default_time_format', 'label' => 'Default Time Format', 'type' => 'select', 'options' => ['H:i' => '24 Hour', 'h:i A' => '12 Hour']],
                ['key' => 'app.default_theme', 'label' => 'Default Theme', 'type' => 'select', 'options' => ['light' => 'Light', 'dark' => 'Dark', 'system' => 'System']],
                ['key' => 'app.records_per_page', 'label' => 'Records Per Page', 'type' => 'number'],
                ['key' => 'app.enable_activity_logging', 'label' => 'Enable Activity Logging', 'type' => 'boolean', 'input' => 'toggle'],
            ],
        ],

        'security-settings' => [
            'label' => 'Security Settings',
            'description' => 'Authentication and security hardening controls.',
            'icon' => 'shield-check',
            'color' => 'red',
            'fields' => [
                ['key' => 'security.two_factor_required', 'label' => '2FA Required', 'type' => 'boolean', 'input' => 'toggle'],
                ['key' => 'security.password_expiry_days', 'label' => 'Password Expiry (Days)', 'type' => 'number'],
                ['key' => 'security.max_login_attempts', 'label' => 'Max Login Attempts', 'type' => 'number'],
                ['key' => 'security.lockout_minutes', 'label' => 'Lockout Minutes', 'type' => 'number'],
                ['key' => 'security.session_timeout_minutes', 'label' => 'Session Timeout (Minutes)', 'type' => 'number'],
                ['key' => 'security.force_ssl', 'label' => 'Force SSL', 'type' => 'boolean', 'input' => 'toggle'],
                ['key' => 'security.allowed_ip_ranges', 'label' => 'Allowed IP Ranges (JSON)', 'type' => 'json', 'input' => 'textarea'],
            ],
        ],

        // ---------------------------------------------------------------------
        // NewsPilot AI domain settings (Phase 1)
        // ---------------------------------------------------------------------

        'site-settings' => [
            'label' => 'Site Identity',
            'description' => 'Public site name, tagline, copyright, and reading-experience defaults.',
            'icon' => 'globe',
            'color' => 'indigo',
            'fields' => [
                ['key' => 'site.name', 'label' => 'Site Name', 'type' => 'text', 'default' => 'NewsPilot AI'],
                ['key' => 'site.tagline', 'label' => 'Tagline', 'type' => 'text', 'default' => 'AI-powered news, blog & magazine portal'],
                ['key' => 'site.description', 'label' => 'Default Site Description', 'type' => 'text', 'input' => 'textarea'],
                ['key' => 'site.copyright', 'label' => 'Copyright Text', 'type' => 'text'],
                ['key' => 'site.contact_email', 'label' => 'Contact Email', 'type' => 'text'],
                ['key' => 'site.posts_per_page', 'label' => 'Posts Per Page', 'type' => 'number', 'default' => 12],
                ['key' => 'site.excerpt_length', 'label' => 'Excerpt Length (Words)', 'type' => 'number', 'default' => 30],
                ['key' => 'site.show_reading_time', 'label' => 'Show Reading Time', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'site.show_author_box', 'label' => 'Show Author Box', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'site.show_view_counter', 'label' => 'Show View Counter', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'site.enable_likes', 'label' => 'Enable Likes', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'site.use_locale_prefix_for_default', 'label' => 'Use /{locale} Prefix For Default Language', 'type' => 'boolean', 'input' => 'toggle', 'default' => false],
            ],
        ],

        'seo-defaults' => [
            'label' => 'SEO Defaults',
            'description' => 'Default meta tags, Open Graph image, analytics codes, schema organisation.',
            'icon' => 'search',
            'color' => 'emerald',
            'fields' => [
                ['key' => 'seo.default_meta_title', 'label' => 'Default Meta Title', 'type' => 'text'],
                ['key' => 'seo.default_meta_description', 'label' => 'Default Meta Description', 'type' => 'text', 'input' => 'textarea'],
                ['key' => 'seo.default_og_image', 'label' => 'Default Open Graph Image', 'type' => 'image'],
                ['key' => 'seo.organization_name', 'label' => 'Publisher / Organization Name', 'type' => 'text'],
                ['key' => 'seo.organization_logo', 'label' => 'Publisher Logo (Schema)', 'type' => 'image'],
                ['key' => 'seo.twitter_handle', 'label' => 'X / Twitter @handle', 'type' => 'text'],
                ['key' => 'seo.facebook_app_id', 'label' => 'Facebook App ID', 'type' => 'text'],
                ['key' => 'seo.google_analytics_id', 'label' => 'Google Analytics (GA4) ID', 'type' => 'text'],
                ['key' => 'seo.google_search_console_code', 'label' => 'Google Search Console Verification', 'type' => 'text'],
                ['key' => 'seo.bing_verification_code', 'label' => 'Bing Site Verification', 'type' => 'text'],
                ['key' => 'seo.facebook_pixel_id', 'label' => 'Facebook Pixel ID', 'type' => 'text'],
                ['key' => 'seo.enable_sitemap', 'label' => 'Enable XML Sitemap', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'seo.enable_news_sitemap', 'label' => 'Enable Google News Sitemap', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'seo.enable_image_sitemap', 'label' => 'Enable Image Sitemap', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'seo.robots_default', 'label' => 'Default Robots Directive', 'type' => 'select', 'options' => [
                    'index,follow' => 'index, follow',
                    'noindex,follow' => 'noindex, follow',
                    'index,nofollow' => 'index, nofollow',
                    'noindex,nofollow' => 'noindex, nofollow',
                ], 'default' => 'index,follow'],
            ],
        ],

        'ai-providers' => [
            'label' => 'AI Providers',
            'description' => 'AI provider API keys (encrypted), default model, fallback chain, cost ceilings and quotas.',
            'icon' => 'sparkles',
            'color' => 'violet',
            'fields' => [
                ['key' => 'ai.default_provider', 'label' => 'Default AI Provider', 'type' => 'select', 'options' => [
                    'openai' => 'OpenAI',
                    'gemini' => 'Google Gemini',
                    'claude' => 'Anthropic Claude',
                    'openrouter' => 'OpenRouter',
                ], 'default' => 'openai'],
                ['key' => 'ai.default_model', 'label' => 'Default Model', 'type' => 'text', 'default' => 'gpt-4o-mini'],
                ['key' => 'ai.fallback_chain', 'label' => 'Fallback Chain (JSON array)', 'type' => 'json', 'input' => 'textarea', 'default' => ['openai', 'gemini']],
                ['key' => 'ai.openai_api_key', 'label' => 'OpenAI API Key', 'type' => 'encrypted'],
                ['key' => 'ai.openai_base_url', 'label' => 'OpenAI Base URL', 'type' => 'text', 'default' => 'https://api.openai.com/v1'],
                ['key' => 'ai.gemini_api_key', 'label' => 'Google Gemini API Key', 'type' => 'encrypted'],
                ['key' => 'ai.claude_api_key', 'label' => 'Anthropic Claude API Key', 'type' => 'encrypted'],
                ['key' => 'ai.openrouter_api_key', 'label' => 'OpenRouter API Key', 'type' => 'encrypted'],
                ['key' => 'ai.default_temperature', 'label' => 'Default Temperature', 'type' => 'number', 'default' => 0.7],
                ['key' => 'ai.default_max_tokens', 'label' => 'Default Max Tokens', 'type' => 'number', 'default' => 2000],
                ['key' => 'ai.streaming_enabled', 'label' => 'Enable AI Streaming', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'ai.moderation_enabled', 'label' => 'Enable AI Moderation', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'ai.user_monthly_cost_ceiling_usd', 'label' => 'Per-User Monthly Cost Ceiling (USD)', 'type' => 'number', 'default' => 25],
                ['key' => 'ai.platform_monthly_cost_ceiling_usd', 'label' => 'Platform Monthly Cost Ceiling (USD)', 'type' => 'number', 'default' => 1000],
                ['key' => 'ai.quota_per_role', 'label' => 'Quota Per Role (JSON; null = unlimited)', 'type' => 'json', 'input' => 'textarea', 'default' => [
                    'Super Admin' => null,
                    'Admin' => 10000,
                    'Editor' => 500,
                    'Author' => 100,
                    'Contributor' => 20,
                ]],
            ],
        ],

        'content-settings' => [
            'label' => 'Content Settings',
            'description' => 'Defaults for post creation, comments, related content and reading experience.',
            'icon' => 'newspaper',
            'color' => 'sky',
            'fields' => [
                ['key' => 'content.default_post_status', 'label' => 'Default New Post Status', 'type' => 'select', 'options' => [
                    'draft' => 'Draft',
                    'pending_review' => 'Pending Review',
                ], 'default' => 'draft'],
                ['key' => 'content.auto_approve_trusted_authors', 'label' => 'Auto-Approve Trusted Authors', 'type' => 'boolean', 'input' => 'toggle', 'default' => false],
                ['key' => 'content.related_posts_count', 'label' => 'Related Posts Count', 'type' => 'number', 'default' => 4],
                ['key' => 'content.enable_table_of_contents', 'label' => 'Enable Table of Contents', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'content.enable_reading_progress', 'label' => 'Enable Reading Progress Bar', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'content.enable_share_buttons', 'label' => 'Enable Share Buttons', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'content.allow_guest_comments', 'label' => 'Allow Guest Comments', 'type' => 'boolean', 'input' => 'toggle', 'default' => false],
                ['key' => 'content.moderate_comments', 'label' => 'Hold Comments For Moderation', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'content.comment_close_after_days', 'label' => 'Auto-Close Comments After (Days, 0 = never)', 'type' => 'number', 'default' => 0],
                ['key' => 'content.breaking_news_default_hours', 'label' => 'Breaking News Default Duration (Hours)', 'type' => 'number', 'default' => 6],
            ],
        ],

        'monetization-settings' => [
            'label' => 'Monetization',
            'description' => 'AdSense, sponsored content disclosure, paywall preview settings.',
            'icon' => 'dollar-sign',
            'color' => 'amber',
            'fields' => [
                ['key' => 'monetization.adsense_publisher_id', 'label' => 'AdSense Publisher ID', 'type' => 'text'],
                ['key' => 'monetization.adsense_auto_ads_enabled', 'label' => 'Enable AdSense Auto Ads', 'type' => 'boolean', 'input' => 'toggle', 'default' => false],
                ['key' => 'monetization.sponsored_label', 'label' => 'Sponsored Content Label', 'type' => 'text', 'default' => 'Sponsored'],
                ['key' => 'monetization.affiliate_disclosure_text', 'label' => 'Affiliate Disclosure Text', 'type' => 'text', 'input' => 'textarea'],
                ['key' => 'monetization.enable_premium_content', 'label' => 'Enable Premium / Paywall Mode', 'type' => 'boolean', 'input' => 'toggle', 'default' => false],
                ['key' => 'monetization.premium_preview_paragraphs', 'label' => 'Free Paragraphs Before Paywall', 'type' => 'number', 'default' => 3],
            ],
        ],

        'newsletter-settings' => [
            'label' => 'Newsletter',
            'description' => 'Sender identity, double opt-in, auto-send rules, weekly digest.',
            'icon' => 'send',
            'color' => 'pink',
            'fields' => [
                ['key' => 'newsletter.enabled', 'label' => 'Enable Newsletter Module', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'newsletter.from_name', 'label' => 'Sender Name', 'type' => 'text'],
                ['key' => 'newsletter.from_address', 'label' => 'Sender Email', 'type' => 'text'],
                ['key' => 'newsletter.double_opt_in', 'label' => 'Require Double Opt-In', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'newsletter.send_on_new_post', 'label' => 'Auto-Send On New Post', 'type' => 'boolean', 'input' => 'toggle', 'default' => false],
                ['key' => 'newsletter.send_on_breaking_news', 'label' => 'Auto-Send On Breaking News', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'newsletter.weekly_digest_enabled', 'label' => 'Enable Weekly Digest', 'type' => 'boolean', 'input' => 'toggle', 'default' => false],
                ['key' => 'newsletter.weekly_digest_day', 'label' => 'Weekly Digest Day', 'type' => 'select', 'options' => [
                    'monday' => 'Monday',
                    'tuesday' => 'Tuesday',
                    'wednesday' => 'Wednesday',
                    'thursday' => 'Thursday',
                    'friday' => 'Friday',
                    'saturday' => 'Saturday',
                    'sunday' => 'Sunday',
                ], 'default' => 'monday'],
            ],
        ],

        'social-settings' => [
            'label' => 'Social Profiles',
            'description' => 'Social media profile URLs and per-network share button toggles.',
            'icon' => 'share-2',
            'color' => 'teal',
            'fields' => [
                ['key' => 'social.facebook_url', 'label' => 'Facebook URL', 'type' => 'text'],
                ['key' => 'social.twitter_url', 'label' => 'X / Twitter URL', 'type' => 'text'],
                ['key' => 'social.linkedin_url', 'label' => 'LinkedIn URL', 'type' => 'text'],
                ['key' => 'social.instagram_url', 'label' => 'Instagram URL', 'type' => 'text'],
                ['key' => 'social.youtube_url', 'label' => 'YouTube URL', 'type' => 'text'],
                ['key' => 'social.pinterest_url', 'label' => 'Pinterest URL', 'type' => 'text'],
                ['key' => 'social.telegram_url', 'label' => 'Telegram URL', 'type' => 'text'],
                ['key' => 'social.whatsapp_number', 'label' => 'WhatsApp Number', 'type' => 'text'],
                ['key' => 'social.share_facebook_enabled', 'label' => 'Show Facebook Share Button', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'social.share_twitter_enabled', 'label' => 'Show X / Twitter Share Button', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'social.share_linkedin_enabled', 'label' => 'Show LinkedIn Share Button', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'social.share_whatsapp_enabled', 'label' => 'Show WhatsApp Share Button', 'type' => 'boolean', 'input' => 'toggle', 'default' => true],
                ['key' => 'social.share_telegram_enabled', 'label' => 'Show Telegram Share Button', 'type' => 'boolean', 'input' => 'toggle', 'default' => false],
                ['key' => 'social.share_pinterest_enabled', 'label' => 'Show Pinterest Share Button', 'type' => 'boolean', 'input' => 'toggle', 'default' => false],
            ],
        ],
    ],
];
