<?php

declare(strict_types=1);

namespace App\Services\AI\DataTransferObjects;

/**
 * One question/answer pair generated by GenerateFAQAction.
 */
final readonly class FAQItem
{
    public function __construct(
        public string $question,
        public string $answer,
    ) {}

    /**
     * @param  array<string, mixed>  $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            question: trim((string) ($data['question'] ?? '')),
            answer: trim((string) ($data['answer'] ?? '')),
        );
    }

    /**
     * @return array{question:string, answer:string}
     */
    public function toArray(): array
    {
        return [
            'question' => $this->question,
            'answer' => $this->answer,
        ];
    }
}
