<?php

declare(strict_types=1);

use App\Services\AI\AIManager;
use App\Services\AI\AIUsageTracker;
use App\Services\AI\CircuitBreaker;
use App\Services\AI\Contracts\AIProvider;
use App\Services\AI\DataTransferObjects\CompletionRequest;
use App\Services\AI\DataTransferObjects\CompletionResponse;
use App\Services\AI\DataTransferObjects\TokenUsage;
use App\Services\AI\NullProvider;
use App\Services\SettingService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Cache;

uses(RefreshDatabase::class);

/**
 * Provider that ONLY accepts a specific model — useful for asserting
 * that AIManager substitutes the model when the caller's choice isn't
 * supported by the fallback provider.
 */
class StrictModelProvider implements AIProvider
{
    /**
     * @var list<string>
     */
    public array $capturedModels = [];

    /**
     * @param  list<string>  $models
     */
    public function __construct(
        public string $providerName,
        public array $models,
    ) {}

    public function name(): string
    {
        return $this->providerName;
    }

    public function complete(CompletionRequest $request): CompletionResponse
    {
        $this->capturedModels[] = $request->model;

        if (! in_array($request->model, $this->models, true)) {
            throw new \App\Services\AI\Exceptions\AIProviderException(
                "Model [{$request->model}] not supported by {$this->providerName}.",
            );
        }

        return new CompletionResponse(
            content: "Generated by {$this->providerName} using {$request->model}",
            usage: new TokenUsage(10, 20, 30, 0.0001),
            providerName: $this->providerName,
            model: $request->model,
        );
    }

    public function availableModels(): array
    {
        return $this->models;
    }

    public function isHealthy(): bool
    {
        return true;
    }

    public function estimateCost(string $model, int $promptTokens, int $completionTokens): float
    {
        return 0.0;
    }
}

beforeEach(function (): void {
    Cache::flush();
});

test('manager substitutes model when fallback provider does not support the requested one', function (): void {
    // Primary 'fake-openai' — rejects everything (simulates quota error).
    app()->bind('Test\\AI\\StrictPrimary', fn () => new StrictModelProvider('fake-openai', []));

    // Fallback 'fake-gemini' — only supports 'gemini-flash'.
    app()->bind('Test\\AI\\StrictFallback', fn () => new StrictModelProvider('fake-gemini', ['gemini-flash']));

    $manager = new AIManager(
        circuitBreaker: app(CircuitBreaker::class),
        usageTracker: app(AIUsageTracker::class),
        settings: app(SettingService::class),
        container: app(),
    );

    $manager->register('fake-openai', 'Test\\AI\\StrictPrimary');
    $manager->register('fake-gemini', 'Test\\AI\\StrictFallback');
    $manager->register(NullProvider::NAME, NullProvider::class);

    app(SettingService::class)->set('ai.fallback_chain', ['fake-openai', 'fake-gemini']);
    app(SettingService::class)->reloadCache();

    $response = $manager->complete(new CompletionRequest(
        model: 'gpt-4o-mini',           // OpenAI-flavoured model name
        systemPrompt: 'sys',
        userPrompt: 'hi',
        featureKey: 'article_writer',
    ));

    expect($response->providerName)->toBe('fake-gemini');
    expect($response->model)->toBe('gemini-flash');           // ← substituted, not the requested 'gpt-4o-mini'
    expect($response->content)->toContain('fake-gemini using gemini-flash');
});

test('no substitution when the requested model is already supported', function (): void {
    app()->bind('Test\\AI\\StrictNative', fn () => new StrictModelProvider('fake-openai', ['gpt-4o-mini', 'gpt-4o']));

    $manager = new AIManager(
        circuitBreaker: app(CircuitBreaker::class),
        usageTracker: app(AIUsageTracker::class),
        settings: app(SettingService::class),
        container: app(),
    );

    $manager->register('fake-openai', 'Test\\AI\\StrictNative');
    $manager->register(NullProvider::NAME, NullProvider::class);

    app(SettingService::class)->set('ai.fallback_chain', ['fake-openai']);
    app(SettingService::class)->reloadCache();

    $response = $manager->complete(new CompletionRequest(
        model: 'gpt-4o-mini',
        systemPrompt: 'sys',
        userPrompt: 'hi',
        featureKey: 'article_writer',
    ));

    expect($response->providerName)->toBe('fake-openai');
    expect($response->model)->toBe('gpt-4o-mini');            // ← unchanged
});

test('substitution metadata is preserved in the usage log for traceability', function (): void {
    $user = \App\Models\User::factory()->create();

    app()->bind('Test\\AI\\Substitute', fn () => new StrictModelProvider('fake-gemini', ['gemini-flash']));

    $manager = new AIManager(
        circuitBreaker: app(CircuitBreaker::class),
        usageTracker: app(AIUsageTracker::class),
        settings: app(SettingService::class),
        container: app(),
    );

    $manager->register('fake-gemini', 'Test\\AI\\Substitute');
    $manager->register(NullProvider::NAME, NullProvider::class);

    app(SettingService::class)->set('ai.fallback_chain', ['fake-gemini']);
    app(SettingService::class)->reloadCache();

    $manager->complete(new CompletionRequest(
        model: 'gpt-4o-mini',
        systemPrompt: 'sys',
        userPrompt: 'hi',
        featureKey: 'article_writer',
        userId: $user->id,
    ));

    $log = \App\Models\AIUsageLog::query()->where('user_id', $user->id)->latest()->first();

    expect($log)->not->toBeNull();
    expect($log->model)->toBe('gemini-flash');
    expect($log->request_metadata['model_substituted_from'] ?? null)->toBe('gpt-4o-mini');
    expect($log->request_metadata['model_substituted_to'] ?? null)->toBe('gemini-flash');
    expect($log->request_metadata['substituted_by_provider'] ?? null)->toBe('fake-gemini');
});
